spring.application.name=Exercicio15

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.5
spring.ai.google.genai.chat.options.top-k=20
spring.ai.google.genai.chat.options.top-p=0.9

spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console