spring.application.name=Exercicio12
spring.datasource.url=jdbc:mysql://localhost:3306/pessoa_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
